pdf-engine: lualatex
number-sections: true
top-level-division: chapter # 採番をh2から始める。
variables:
    lang: ja
filters:
    - pandoc-crossref

metadata:
    documentclass: ltjsarticle
    luatexjapresetoptions: fonts-noto-cjk
    figureTitle: "図"
    tableTitle: "表"
    listingTitle: "コード"
    figPrefix: "図"
    eqnPrefix: "式"
    tblPrefix: "表"
    lstPrefix: "コード"
