pdf-engine: lualatex
number-sections: true
filters:
    - pandoc-crossref
metadata:
    listings: true
    documentclass: ltjsarticle
    luatexjapresetoptions: fonts-noto-cjk
    figureTitle: "図"
    tableTitle: "表"
    listingTitle: "コード"
    figPrefix: "図"
    eqnPrefix: "式"
    tblPrefix: "表"
    lstPrefix: "コード"